# Generated by Django 2.2.5 on 2022-11-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_auto_20221120_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertype',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
