# Generated by Django 2.2.5 on 2022-10-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra_user', '0003_auto_20221017_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
    ]
